[platformio]
default_envs = xiaoblesense_adafruit

[env:xiaoblesense_adafruit]
platform = https://github.com/maxgerhardt/platform-nordicnrf52.git#cac6fcf943a41accd2aeb4f3659ae297a73f422e
board = xiaoblesense_adafruit
framework = arduino
monitor_speed = 115200
build_unflags = -Ofast
build_flags = -O2 -fno-fast-math -I../../firmware/src/platform/nrf52
extra_scripts = pre:build_identity.py
